version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

formats:
  - epub
  - htmlzip

sphinx:
  builder: html
  configuration: doc/conf.py

python:
  install:
    - requirements: doc/requirements.txt
    - requirements: requirements.txt
