#!/bin/sh

echo "Running black."
git ls-files | grep "\.py$" |  xargs black

if [ $? -ne 0 ]; then
 echo "Black should pass before commit."
 exit 1
fi

echo "Adding license header."
./.github/scripts/prepend_license.sh

if [ $? -ne 0 ]; then
 echo "Could not add license header."
 exit 1
fi
