name: SageMaker Tests

# All tests in this file:
# 1. Run when launched manually
# 2. Require AWS credentials and launch training jobs

on:
  workflow_dispatch:
    inputs:
      seed:
        description: "Seed for the run"
        required: true
  pull_request:
    branches:
      - main
      - dev

env:
  AWS_DEFAULT_REGION: us-west-2
  AWS_ROLE: ${{ secrets.PROD_AWS_END_TO_END_TEST_ROLE_ARN }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Prepare Inputs
      id: set-matrix
      run: |
        import os
        import json

        target_directory = 'test/integration_tests/configs/suites/main'
        files = [f for f in os.listdir(target_directory) if os.path.isfile(os.path.join(target_directory, f))]
        matrix_json = json.dumps(files)
        print(matrix_json)
        with open('matrix.json', 'w') as f:
            f.write(matrix_json)
        
        name = "matrix"
        value = matrix_json
        with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
          print(f'{name}={value}', file=fh)

      shell: python


  tests:
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        suite: ${{ fromJSON(needs.prepare.outputs.matrix)}}
    uses: ./.github/workflows/run_renate.yml
    with:
      path: test/integration_tests
      script: run_test.py --test-file ${{ matrix.suite }} --seed 0
      requires-aws-credentials: true
    secrets: inherit
